/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormField: typeof import('./src/components/shared/FormField.vue')['default']
    MultiStepForm: typeof import('./src/components/MultiStepForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepFour: typeof import('./src/components/steps/StepFour.vue')['default']
    StepOne: typeof import('./src/components/steps/StepOne.vue')['default']
    StepThree: typeof import('./src/components/steps/StepThree.vue')['default']
    StepTwo: typeof import('./src/components/steps/StepTwo.vue')['default']
    ThankYou: typeof import('./src/components/steps/ThankYou.vue')['default']
  }
}
